#importonce

.const VIC_II_BASE_ADDRESS = $d000
.const X_COORD_SPRITE_0   = VIC_II_BASE_ADDRESS
.const Y_COORD_SPRITE_0   = VIC_II_BASE_ADDRESS + $01
.const X_COORD_SPRITE_1   = VIC_II_BASE_ADDRESS + $02
.const Y_COORD_SPRITE_1   = VIC_II_BASE_ADDRESS + $03
.const CONTROL_REGISTER_1 = VIC_II_BASE_ADDRESS + $11
.const RASTER_COUNTER     = VIC_II_BASE_ADDRESS + $12
.const SPRITE_ENABLED     = VIC_II_BASE_ADDRESS + $15
.const CONTROL_REGISTER_2 = VIC_II_BASE_ADDRESS + $16
.const MEMORY_POINTERS    = VIC_II_BASE_ADDRESS + $18
.const BORDER_COLOR       = VIC_II_BASE_ADDRESS + $20
.const BACKGROUND_COLOR_0 = VIC_II_BASE_ADDRESS + $21
.const SPRITE_COLOR_0     = VIC_II_BASE_ADDRESS + $27
.const SPRITE_COLOR_1     = VIC_II_BASE_ADDRESS + $28

.const SCREEN_RAM         = $0400
.const COLOR_RAM          = $D800
.const BITMAP_RAM         = $2000

.const CIA_1_BASE_ADDRESS = $dc00
.const JOYSTICK_2         = CIA_1_BASE_ADDRESS
.const JOYSTICK_1         = CIA_1_BASE_ADDRESS + $1
